# Generated by Django 2.0.4 on 2018-05-10 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('has_math', models.BooleanField(verbose_name='是否有数学类课程')),
                ('detail', models.TextField(default='', verbose_name='数学具体课程')),
                ('is_first', models.BooleanField(verbose_name='是否第一次修读')),
                ('is_approved', models.NullBooleanField(default=None, verbose_name='是否通过审核')),
                ('is_interviewed', models.NullBooleanField(default=None, verbose_name='是否通过面试')),
                ('is_changed', models.NullBooleanField(default=None, verbose_name='是否调剂')),
                ('is_cashed', models.NullBooleanField(default=None, verbose_name='是否扣款')),
                ('suggest', models.TextField(default='', verbose_name='审核意见')),
            ],
            options={
                'verbose_name': '申请表',
                'verbose_name_plural': '申请表',
            },
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='学院名称')),
                ('desc', models.CharField(max_length=150, verbose_name='学院介绍')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='专业名称')),
                ('desc', models.TextField(verbose_name='专业介绍')),
                ('type', models.CharField(default='两年', max_length=50, verbose_name='学制')),
                ('collage', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='major.Collage', verbose_name='申请学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='学号/工号')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=3, verbose_name='性别')),
                ('session', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='年级')),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='联系电话')),
                ('homeaddr', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='家庭住址')),
                ('collage', models.ManyToManyField(blank=True, to='major.Collage', verbose_name='学院')),
                ('major', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='major.Major', verbose_name='专业')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生/员工资料',
                'verbose_name_plural': '学生/员工资料',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('collage', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='major.Collage', verbose_name='申请学院')),
                ('major', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='major.Major', verbose_name='申请专业')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '双学位学生信息记录表',
                'verbose_name_plural': '双学位学生信息记录表',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='upload_dir', verbose_name='专业培养方案')),
                ('desc', models.TextField(default='', verbose_name='通知内容')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='通知人')),
            ],
            options={
                'verbose_name': '通知栏',
                'verbose_name_plural': '通知栏',
            },
        ),
        migrations.AddField(
            model_name='approve',
            name='major',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='major.Major', verbose_name='申请专业'),
        ),
        migrations.AddField(
            model_name='approve',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
    ]
