# Generated by Django 2.0.4 on 2018-05-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='studentcount',
            field=models.CharField(default='0', max_length=50, verbose_name='专业接纳人数'),
        ),
    ]
