# Generated by Django 2.0.4 on 2018-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_major_studentcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='suggest',
            field=models.TextField(blank=True, default='', null=True, verbose_name='审核意见'),
        ),
    ]
