# Generated by Django 2.0.4 on 2018-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0003_auto_20180511_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='detail',
            field=models.TextField(blank=True, default='', null=True, verbose_name='数学具体课程'),
        ),
    ]
